/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Source that activated an agent skill.
 */

export const AgentSkillActivationSource = {
    SLASH: 'slash',
    TOOL: 'tool'
} as const;

export type AgentSkillActivationSource = typeof AgentSkillActivationSource[keyof typeof AgentSkillActivationSource];
