/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BillingSpeed } from './billing-speed';
// May contain unused imports in some cases
// @ts-ignore
import type { PermissionLevel } from './permission-level';
// May contain unused imports in some cases
// @ts-ignore
import type { ReasoningEffort } from './reasoning-effort';

/**
 * Properties for the `agent.session.activated` event.
 */
export interface AgentSessionActivatedProps {
    'thread_id'?: string | null;
    'provider'?: string | null;
    'model'?: string | null;
    'reasoning_effort'?: ReasoningEffort | null;
    'speed'?: BillingSpeed | null;
    'permission_level'?: PermissionLevel | null;
    'capabilities': Array<AgentSessionActivatedPropsCapabilitiesEnum>;
    'visit': number;
}

export const AgentSessionActivatedPropsCapabilitiesEnum = {
    STEER: 'steer'
} as const;

export type AgentSessionActivatedPropsCapabilitiesEnum = typeof AgentSessionActivatedPropsCapabilitiesEnum[keyof typeof AgentSessionActivatedPropsCapabilitiesEnum];
