/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AggregateBillingTotals } from './aggregate-billing-totals';
// May contain unused imports in some cases
// @ts-ignore
import type { BillingByModel } from './billing-by-model';

/**
 * Aggregate token counts and billed totals across all runs since server start.
 */
export interface AggregateBilling {
    'totals': AggregateBillingTotals;
    /**
     * Billing grouped by model.
     */
    'by_model': Array<BillingByModel>;
}
