/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Runtime user authentication method.
 */

export const AuthMethod = {
    GITHUB: 'github',
    DEV_TOKEN: 'dev_token'
} as const;

export type AuthMethod = typeof AuthMethod[keyof typeof AuthMethod];
