/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Repository and workflow selected by an automation.
 */
export interface AutomationTarget {
    /**
     * GitHub repository slug in `owner/repo` form.
     */
    'repository': string;
    /**
     * Branch, tag, or SHA selector resolved when materializing a run.
     */
    'ref': string;
    /**
     * Workflow slug or path resolved in the target repository.
     */
    'workflow': string;
}
