/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Trigger that allows callers to create runs through the automation API.
 */
export interface AutomationApiTrigger {
    'id': string;
    'type': AutomationApiTriggerTypeEnum;
    'enabled': boolean;
}

export const AutomationApiTriggerTypeEnum = {
    API: 'api'
} as const;

export type AutomationApiTriggerTypeEnum = typeof AutomationApiTriggerTypeEnum[keyof typeof AutomationApiTriggerTypeEnum];
