/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BatchRunLifecycleResult } from './batch-run-lifecycle-result';
// May contain unused imports in some cases
// @ts-ignore
import type { BatchRunLifecycleSummary } from './batch-run-lifecycle-summary';

/**
 * Per-run results for a fail-soft batch archive or unarchive request.
 */
export interface BatchRunLifecycleResponse {
    /**
     * Results ordered exactly like the request `run_ids`.
     */
    'results': Array<BatchRunLifecycleResult>;
    'summary': BatchRunLifecycleSummary;
}
