/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Aggregate counts for a batch archive or unarchive request.
 */
export interface BatchRunLifecycleSummary {
    /**
     * Number of requested run IDs.
     */
    'requested': number;
    /**
     * Number of item results with `ok=true`.
     */
    'succeeded': number;
    /**
     * Number of item results with `ok=false`.
     */
    'failed': number;
}
