/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Token counts with optional billed USD micros totals.
 */
export interface BilledTokenCounts {
    /**
     * Number of input tokens consumed.
     */
    'input_tokens': number;
    /**
     * Number of output tokens generated.
     */
    'output_tokens': number;
    /**
     * Total billable tokens aggregated across categories.
     */
    'total_tokens': number;
    /**
     * Number of reasoning tokens.
     */
    'reasoning_tokens': number;
    /**
     * Number of cache read tokens.
     */
    'cache_read_tokens': number;
    /**
     * Number of cache write tokens.
     */
    'cache_write_tokens': number;
    /**
     * Billed USD amount in micros.
     */
    'total_usd_micros'?: number | null;
}
