/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Reference to a workflow node in a billing stage row.
 */
export interface BillingStageRef {
    /**
     * Stage identifier (slug).
     */
    'id': string;
    /**
     * Human-readable stage name.
     */
    'name': string;
}
