/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Specific reason a run is blocked on external intervention.
 */

export const BlockedReason = {
    HUMAN_INPUT_REQUIRED: 'human_input_required'
} as const;

export type BlockedReason = typeof BlockedReason[keyof typeof BlockedReason];
