/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Status of a CI check run.
 */

export const CheckRunStatus = {
    SUCCESS: 'success',
    FAILURE: 'failure',
    SKIPPED: 'skipped',
    PENDING: 'pending',
    QUEUED: 'queued'
} as const;

export type CheckRunStatus = typeof CheckRunStatus[keyof typeof CheckRunStatus];
