/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Terminal state for a command execution.
 */

export const CommandTermination = {
    EXITED: 'exited',
    TIMED_OUT: 'timed_out',
    CANCELLED: 'cancelled'
} as const;

export type CommandTermination = typeof CommandTermination[keyof typeof CommandTermination];
