/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A content part within a message, discriminated by `kind`.
 */
export interface CompletionContentPart {
    /**
     * Content part type: text, image, tool_call, tool_result, thinking, etc.
     */
    'kind': string;
    'data'?: any;
}
