/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Controls how the model selects tools.
 */
export interface CompletionToolChoice {
    /**
     * Tool selection mode.
     */
    'mode': CompletionToolChoiceModeEnum;
    /**
     * Required when mode is \"named\".
     */
    'tool_name'?: string;
}

export const CompletionToolChoiceModeEnum = {
    AUTO: 'auto',
    NONE: 'none',
    REQUIRED: 'required',
    NAMED: 'named'
} as const;

export type CompletionToolChoiceModeEnum = typeof CompletionToolChoiceModeEnum[keyof typeof CompletionToolChoiceModeEnum];
