/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CompletionMessage } from './completion-message';
// May contain unused imports in some cases
// @ts-ignore
import type { CompletionUsage } from './completion-usage';

export interface CompletionResponse {
    'id': string;
    'model': string;
    'message': CompletionMessage;
    /**
     * Why generation stopped (end_turn, max_tokens, tool_calls).
     */
    'stop_reason': string;
    'usage': CompletionUsage;
    'output'?: any;
}
