/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SecretType } from './secret-type';

/**
 * Request to store or update a secret.
 */
export interface CreateSecretRequest {
    /**
     * Secret name or destination path for file secrets.
     */
    'name': string;
    /**
     * The secret value to store.
     */
    'value': string;
    'type': SecretType;
    /**
     * Optional operator-facing description of the secret.
     */
    'description'?: string;
}
