/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request body for creating a run pull request.
 */
export interface CreateRunPullRequestRequest {
    /**
     * Create the pull request even if the run did not finish with succeeded or partially_succeeded.
     */
    'force': boolean;
    /**
     * Optional model override for generating the pull request description.
     */
    'model'?: string | null;
}
