/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * One top-level disk usage category.
 */
export interface DiskUsageSummaryRow {
    /**
     * Category name, such as runs or logs.
     */
    'type'?: string;
    /**
     * Number of items in the category.
     */
    'count'?: number;
    /**
     * Number of active items when applicable.
     */
    'active'?: number | null;
    /**
     * Total bytes used by the category.
     */
    'size_bytes'?: number;
    /**
     * Bytes reclaimable by pruning the category.
     */
    'reclaimable_bytes'?: number | null;
}
