/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Per-run disk usage information.
 */
export interface DiskUsageRunRow {
    /**
     * Run identifier.
     */
    'run_id'?: string;
    /**
     * Workflow display name.
     */
    'workflow_name'?: string;
    /**
     * Current run status.
     */
    'status'?: string;
    /**
     * Human-readable start timestamp.
     */
    'start_time'?: string;
    /**
     * Size used by the run scratch directory.
     */
    'size_bytes'?: number;
    /**
     * Whether the run is inactive and reclaimable.
     */
    'reclaimable'?: boolean;
}
