/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DiskUsageRunRow } from './disk-usage-run-row';
// May contain unused imports in some cases
// @ts-ignore
import type { DiskUsageSummaryRow } from './disk-usage-summary-row';

/**
 * Disk usage summary for server-managed data.
 */
export interface DiskUsageResponse {
    'summary'?: Array<DiskUsageSummaryRow>;
    /**
     * Total size of all tracked system data.
     */
    'total_size_bytes'?: number;
    /**
     * Total bytes reclaimable by deleting inactive runs and logs.
     */
    'total_reclaimable_bytes'?: number;
    /**
     * Per-run usage rows when verbose output is requested.
     */
    'runs'?: Array<DiskUsageRunRow> | null;
}
