/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ErrorResponseEntry } from './error-response-entry';

/**
 * Standard error response containing one or more error entries.
 */
export interface ErrorResponse {
    /**
     * List of error entries.
     */
    'errors': Array<ErrorResponseEntry>;
    /**
     * Server-generated request identifier; matches the x-request-id response header.
     */
    'request_id'?: string;
    /**
     * Optional list of runtime env keys that were written before an install failure. Currently populated by `POST /install/finish` failure responses only.
     */
    'leftover_env_keys'?: Array<string>;
    /**
     * Optional list of runtime env keys that were actually removed before an install failure. Currently populated by `POST /install/finish` failure responses only.
     */
    'removed_env_keys'?: Array<string>;
}
