/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A single error entry in an error response.
 */
export interface ErrorResponseEntry {
    /**
     * HTTP status code as a string.
     */
    'status': string;
    /**
     * Short error classification.
     */
    'title': string;
    /**
     * Human-readable error description.
     */
    'detail': string;
    /**
     * Optional machine-readable error code for structured client handling.
     */
    'code'?: string;
    /**
     * Server-generated request identifier; matches the x-request-id response header.
     */
    'request_id'?: string;
}
