/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ExecuteQueryResponseRowsInnerInner } from './execute-query-response-rows-inner-inner';

/**
 * Columnar result set from an executed query.
 */
export interface ExecuteQueryResponse {
    /**
     * Column names in the result set.
     */
    'columns': Array<string>;
    /**
     * Result rows, each an array of values matching the column order.
     */
    'rows': Array<Array<ExecuteQueryResponseRowsInnerInner>>;
    /**
     * Query execution time in seconds.
     */
    'elapsed': number;
    /**
     * Number of rows returned.
     */
    'row_count': number;
}
