/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Redacted tail of command stdout/stderr captured for diagnostics.
 */
export interface ExecOutputTail {
    'stdout'?: string | null;
    'stderr'?: string | null;
    'stdout_truncated'?: boolean;
    'stderr_truncated'?: boolean;
}
