/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Product-level classification for grouping and retry policy.
 */

export const FailureCategory = {
    TRANSIENT_INFRA: 'transient_infra',
    DETERMINISTIC: 'deterministic',
    BUDGET_EXHAUSTED: 'budget_exhausted',
    COMPILATION_LOOP: 'compilation_loop',
    CANCELED: 'canceled',
    STRUCTURAL: 'structural'
} as const;

export type FailureCategory = typeof FailureCategory[keyof typeof FailureCategory];
