/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A previously executed query in the history log.
 */
export interface HistoryEntry {
    /**
     * Unique history entry identifier.
     */
    'id': string;
    /**
     * SQL query that was executed.
     */
    'sql': string;
    /**
     * ISO 8601 timestamp of execution.
     */
    'timestamp': string;
    /**
     * Query execution time in seconds.
     */
    'elapsed': number;
    /**
     * Number of rows returned.
     */
    'row_count': number;
}
