/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const HookEvent = {
    RUN_START: 'run_start',
    RUN_COMPLETE: 'run_complete',
    RUN_FAILED: 'run_failed',
    STAGE_START: 'stage_start',
    STAGE_COMPLETE: 'stage_complete',
    STAGE_FAILED: 'stage_failed',
    STAGE_RETRYING: 'stage_retrying',
    EDGE_SELECTED: 'edge_selected',
    PARALLEL_START: 'parallel_start',
    PARALLEL_COMPLETE: 'parallel_complete',
    SANDBOX_READY: 'sandbox_ready',
    SANDBOX_CLEANUP: 'sandbox_cleanup',
    CHECKPOINT_SAVED: 'checkpoint_saved',
    PRE_TOOL_USE: 'pre_tool_use',
    POST_TOOL_USE: 'post_tool_use',
    POST_TOOL_USE_FAILURE: 'post_tool_use_failure'
} as const;

export type HookEvent = typeof HookEvent[keyof typeof HookEvent];
