/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Redacted summary of the object-store mode selected during browser install.
 */
export interface InstallObjectStoreSummary {
    'provider': InstallObjectStoreSummaryProviderEnum;
    'root'?: string;
    'bucket'?: string;
    'region'?: string;
    'credential_mode'?: InstallObjectStoreSummaryCredentialModeEnum;
    'manual_credentials_saved'?: boolean;
}

export const InstallObjectStoreSummaryProviderEnum = {
    LOCAL: 'local',
    S3: 's3'
} as const;

export type InstallObjectStoreSummaryProviderEnum = typeof InstallObjectStoreSummaryProviderEnum[keyof typeof InstallObjectStoreSummaryProviderEnum];
export const InstallObjectStoreSummaryCredentialModeEnum = {
    RUNTIME: 'runtime',
    ACCESS_KEY: 'access_key'
} as const;

export type InstallObjectStoreSummaryCredentialModeEnum = typeof InstallObjectStoreSummaryCredentialModeEnum[keyof typeof InstallObjectStoreSummaryCredentialModeEnum];
