/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Response returned after install outputs are persisted successfully.
 */
export interface InstallFinishResponse {
    'status': InstallFinishResponseStatusEnum;
    'restart_url': string;
    /**
     * Dev token used to bootstrap login. Only included when the operator chose the personal access token flow; GitHub App installs rely on OAuth and do not receive a dev token.
     */
    'dev_token'?: string;
}

export const InstallFinishResponseStatusEnum = {
    COMPLETING: 'completing'
} as const;

export type InstallFinishResponseStatusEnum = typeof InstallFinishResponseStatusEnum[keyof typeof InstallFinishResponseStatusEnum];
