/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { InstallGithubAppOwner } from './install-github-app-owner';

/**
 * Redacted summary of the GitHub install strategy selected during browser install.
 */
export interface InstallGithubSummary {
    'strategy': InstallGithubSummaryStrategyEnum;
    'username'?: string;
    'owner'?: InstallGithubAppOwner;
    'app_name'?: string;
    'slug'?: string;
    'allowed_username'?: string;
}

export const InstallGithubSummaryStrategyEnum = {
    TOKEN: 'token',
    APP: 'app'
} as const;

export type InstallGithubSummaryStrategyEnum = typeof InstallGithubSummaryStrategyEnum[keyof typeof InstallGithubSummaryStrategyEnum];
