/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { InstallLlmProviderInput } from './install-llm-provider-input';

/**
 * LLM providers selected during browser install. An empty `providers` list explicitly marks the LLM step as completed and skipped.
 */
export interface InstallLlmProvidersInput {
    /**
     * LLM providers to persist. An empty list records an explicit skip: the LLM step is marked complete with zero credentials.
     */
    'providers': Array<InstallLlmProviderInput>;
}
