/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { InstallGithubAppOwner } from './install-github-app-owner';

/**
 * Input required to build the browser-install GitHub App manifest.
 */
export interface InstallGithubAppManifestInput {
    'owner': InstallGithubAppOwner;
    'app_name': string;
    'allowed_username': string;
}
