/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { InstallGithubSummary } from './install-github-summary';
// May contain unused imports in some cases
// @ts-ignore
import type { InstallLlmSummary } from './install-llm-summary';
// May contain unused imports in some cases
// @ts-ignore
import type { InstallObjectStoreSummary } from './install-object-store-summary';
// May contain unused imports in some cases
// @ts-ignore
import type { InstallPrefill } from './install-prefill';
// May contain unused imports in some cases
// @ts-ignore
import type { InstallSandboxSummary } from './install-sandbox-summary';
// May contain unused imports in some cases
// @ts-ignore
import type { InstallServerConfigInput } from './install-server-config-input';

/**
 * Current browser-install session snapshot with secrets redacted.
 */
export interface InstallSessionResponse {
    'completed_steps': Array<string>;
    'llm'?: InstallLlmSummary | null;
    'server'?: InstallServerConfigInput | null;
    'object_store'?: InstallObjectStoreSummary | null;
    'sandbox'?: InstallSandboxSummary | null;
    'github'?: InstallGithubSummary | null;
    'prefill': InstallPrefill;
}
