/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ServerIpAllowlistOverrideSettings } from './server-ip-allowlist-override-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { WebhookStrategy } from './webhook-strategy';

export interface IntegrationWebhooksSettings {
    'strategy': WebhookStrategy | null;
    'ip_allowlist': ServerIpAllowlistOverrideSettings | null;
}
