/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Option stored with an interview question in the event log.
 */
export interface InterviewOption {
    /**
     * Machine-readable option key used when submitting an answer.
     */
    'key': string;
    /**
     * Human-readable label displayed to the user.
     */
    'label': string;
    /**
     * Optional untrusted model-authored option description for display.
     */
    'description'?: string | null;
    /**
     * Optional untrusted model-authored option preview captured for clients.
     */
    'preview'?: string | null;
}
