/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ManifestFileRef {
    'type': ManifestFileRefTypeEnum;
    'original': string;
    'from'?: string | null;
}

export const ManifestFileRefTypeEnum = {
    FILE_INLINE: 'file_inline',
    IMPORT: 'import',
    DOCKERFILE: 'dockerfile'
} as const;

export type ManifestFileRefTypeEnum = typeof ManifestFileRefTypeEnum[keyof typeof ManifestFileRefTypeEnum];
