/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface McpTransportSandbox {
    'type': McpTransportSandboxTypeEnum;
    'command': Array<string>;
    'port': number;
    'env': { [key: string]: string; };
}

export const McpTransportSandboxTypeEnum = {
    SANDBOX: 'sandbox'
} as const;

export type McpTransportSandboxTypeEnum = typeof McpTransportSandboxTypeEnum[keyof typeof McpTransportSandboxTypeEnum];
