/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { McpTransportHttp } from './mcp-transport-http';
// May contain unused imports in some cases
// @ts-ignore
import type { McpTransportSandbox } from './mcp-transport-sandbox';
// May contain unused imports in some cases
// @ts-ignore
import type { McpTransportStdio } from './mcp-transport-stdio';

/**
 * @type McpTransport
 */
export type McpTransport = McpTransportHttp | McpTransportSandbox | McpTransportStdio;
