/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AgentMcpToolSummary } from './agent-mcp-tool-summary';

export interface McpServerStatusReady {
    'kind': McpServerStatusReadyKindEnum;
    'tools': Array<AgentMcpToolSummary>;
}

export const McpServerStatusReadyKindEnum = {
    READY: 'ready'
} as const;

export type McpServerStatusReadyKindEnum = typeof McpServerStatusReadyKindEnum[keyof typeof McpServerStatusReadyKindEnum];
