/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Pricing per million tokens in USD.
 */
export interface ModelCosts {
    /**
     * Cost per million input tokens in USD.
     */
    'input_cost_per_mtok': number | null;
    /**
     * Cost per million output tokens in USD.
     */
    'output_cost_per_mtok': number | null;
    /**
     * Cost per million cached input tokens in USD.
     */
    'cache_input_cost_per_mtok': number | null;
}
