/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Token limits for a model.
 */
export interface ModelLimits {
    /**
     * Maximum context window size in tokens.
     */
    'context_window': number;
    /**
     * Maximum output tokens, if known.
     */
    'max_output': number | null;
}
