/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PreRunPushOutcomeFailed } from './pre-run-push-outcome-failed';
// May contain unused imports in some cases
// @ts-ignore
import type { PreRunPushOutcomeNotAttempted } from './pre-run-push-outcome-not-attempted';
// May contain unused imports in some cases
// @ts-ignore
import type { PreRunPushOutcomeSkippedNoRemote } from './pre-run-push-outcome-skipped-no-remote';
// May contain unused imports in some cases
// @ts-ignore
import type { PreRunPushOutcomeSkippedRemoteMismatch } from './pre-run-push-outcome-skipped-remote-mismatch';
// May contain unused imports in some cases
// @ts-ignore
import type { PreRunPushOutcomeSucceeded } from './pre-run-push-outcome-succeeded';

/**
 * @type PreRunPushOutcome
 * Outcome of the CLI\'s best-effort pre-run push.
 */
export type PreRunPushOutcome = { type: 'failed' } & PreRunPushOutcomeFailed | { type: 'not_attempted' } & PreRunPushOutcomeNotAttempted | { type: 'skipped_no_remote' } & PreRunPushOutcomeSkippedNoRemote | { type: 'skipped_remote_mismatch' } & PreRunPushOutcomeSkippedRemoteMismatch | { type: 'succeeded' } & PreRunPushOutcomeSucceeded;
