/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface PreRunPushOutcomeSkippedRemoteMismatch {
    'type': PreRunPushOutcomeSkippedRemoteMismatchTypeEnum;
    'remote': string;
    'repo_origin_url': string;
}

export const PreRunPushOutcomeSkippedRemoteMismatchTypeEnum = {
    SKIPPED_REMOTE_MISMATCH: 'skipped_remote_mismatch'
} as const;

export type PreRunPushOutcomeSkippedRemoteMismatchTypeEnum = typeof PreRunPushOutcomeSkippedRemoteMismatchTypeEnum[keyof typeof PreRunPushOutcomeSkippedRemoteMismatchTypeEnum];
