/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface PreRunPushOutcomeSkippedNoRemote {
    'type': PreRunPushOutcomeSkippedNoRemoteTypeEnum;
}

export const PreRunPushOutcomeSkippedNoRemoteTypeEnum = {
    SKIPPED_NO_REMOTE: 'skipped_no_remote'
} as const;

export type PreRunPushOutcomeSkippedNoRemoteTypeEnum = typeof PreRunPushOutcomeSkippedNoRemoteTypeEnum[keyof typeof PreRunPushOutcomeSkippedNoRemoteTypeEnum];
