/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request body for generating a preview URL from a sandbox port.
 */
export interface PreviewUrlRequest {
    /**
     * Port number exposed by the sandbox.
     */
    'port': number;
    /**
     * Time-to-live for the preview URL in seconds.
     */
    'expires_in_secs': number;
    /**
     * When true, return a signed URL that does not require a preview token header.
     */
    'signed'?: boolean;
}
