/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SystemActorKind } from './system-actor-kind';

export interface PrincipalSystem {
    'kind': PrincipalSystemKindEnum;
    'system_kind': SystemActorKind;
}

export const PrincipalSystemKindEnum = {
    SYSTEM: 'system'
} as const;

export type PrincipalSystemKindEnum = typeof PrincipalSystemKindEnum[keyof typeof PrincipalSystemKindEnum];
