/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface PrincipalAgent {
    'kind': PrincipalAgentKindEnum;
    'session_id'?: string | null;
    'parent_session_id'?: string | null;
    'model'?: string | null;
}

export const PrincipalAgentKindEnum = {
    AGENT: 'agent'
} as const;

export type PrincipalAgentKindEnum = typeof PrincipalAgentKindEnum[keyof typeof PrincipalAgentKindEnum];
