/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface PrincipalSlack {
    'kind': PrincipalSlackKindEnum;
    'team_id': string;
    'user_id': string;
    'user_name'?: string | null;
}

export const PrincipalSlackKindEnum = {
    SLACK: 'slack'
} as const;

export type PrincipalSlackKindEnum = typeof PrincipalSlackKindEnum[keyof typeof PrincipalSlackKindEnum];
