/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * One run matched by a prune preview.
 */
export interface PruneRunEntry {
    /**
     * Run identifier.
     */
    'run_id'?: string;
    /**
     * Scratch directory name for the run.
     */
    'dir_name'?: string;
    /**
     * Workflow display name.
     */
    'workflow_name'?: string;
    /**
     * Bytes used by the run scratch directory.
     */
    'size_bytes'?: number;
}
