/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Filters for system run pruning.
 */
export interface PruneRunsRequest {
    /**
     * Preview matching runs without deleting them.
     */
    'dry_run'?: boolean;
    /**
     * Include runs started before this YYYY-MM-DD prefix.
     */
    'before'?: string;
    /**
     * Filter by workflow name substring.
     */
    'workflow'?: string;
    /**
     * Label filters applied with AND semantics.
     */
    'labels'?: { [key: string]: string; };
    /**
     * Include orphan run directories without run metadata.
     */
    'orphans'?: boolean;
    /**
     * Include only runs older than this duration, such as 24h or 7d.
     */
    'older_than'?: string;
}
