/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PruneRunEntry } from './prune-run-entry';

/**
 * Result of a prune preview or deletion.
 */
export interface PruneRunsResponse {
    /**
     * Whether this response is a dry-run preview.
     */
    'dry_run'?: boolean;
    /**
     * Matched runs when dry-run is enabled.
     */
    'runs'?: Array<PruneRunEntry> | null;
    /**
     * Count of runs matching the prune filters.
     */
    'total_count'?: number;
    /**
     * Total bytes of the matching runs.
     */
    'total_size_bytes'?: number;
    /**
     * Number of runs deleted when dry-run is false.
     */
    'deleted_count'?: number;
    /**
     * Estimated freed bytes when deletion occurs.
     */
    'freed_bytes'?: number;
}
