/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The interaction type of a human-in-the-loop question.
 */

export const QuestionType = {
    YES_NO: 'yes_no',
    MULTIPLE_CHOICE: 'multiple_choice',
    MULTI_SELECT: 'multi_select',
    FREEFORM: 'freeform',
    CONFIRMATION: 'confirmation'
} as const;

export type QuestionType = typeof QuestionType[keyof typeof QuestionType];
