/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RepoCheckResponsePermissions } from './repo-check-response-permissions';

/**
 * Repository access check result.
 */
export interface RepoCheckResponse {
    /**
     * GitHub repository owner.
     */
    'owner': string;
    /**
     * GitHub repository name.
     */
    'name': string;
    /**
     * Whether the server has read-write access to this repository.
     */
    'accessible': boolean;
    /**
     * Default branch name, if accessible.
     */
    'default_branch'?: string | null;
    /**
     * Whether the repository is private, if accessible.
     */
    'private'?: boolean | null;
    'permissions'?: RepoCheckResponsePermissions;
    /**
     * GitHub App installation URL when the repo is not yet accessible.
     */
    'install_url'?: string | null;
}
