/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Response returned after rewind creates a new run.
 */
export interface RewindResponse {
    'source_run_id': string;
    'new_run_id': string;
    'target': string;
    'archived': boolean;
    'archive_error'?: string | null;
}
