/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Collection of API discovery URLs.
 */
export interface RootResponseUrls {
    /**
     * URL of the OpenAPI JSON specification.
     */
    'openapi_url': string;
    /**
     * URL of the current user endpoint.
     */
    'current_user_url': string;
    /**
     * URL of the health check endpoint.
     */
    'health_url': string;
}
