/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BillingByModel } from './billing-by-model';
// May contain unused imports in some cases
// @ts-ignore
import type { RunBillingStage } from './run-billing-stage';
// May contain unused imports in some cases
// @ts-ignore
import type { RunBillingTotals } from './run-billing-totals';

/**
 * Complete billing breakdown for a single run.
 */
export interface RunBilling {
    /**
     * Per-node billing breakdown. Each row sums billing and runtime across all visits of that node.
     */
    'stages': Array<RunBillingStage>;
    'totals': RunBillingTotals;
    /**
     * Billing grouped by model.
     */
    'by_model': Array<BillingByModel>;
}
