/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FailureReason } from './failure-reason';

export interface RunStatusFailed {
    'kind': RunStatusFailedKindEnum;
    'reason': FailureReason;
}

export const RunStatusFailedKindEnum = {
    FAILED: 'failed'
} as const;

export type RunStatusFailedKindEnum = typeof RunStatusFailedKindEnum[keyof typeof RunStatusFailedKindEnum];
