/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A captured artifact file for a run.
 */
export interface RunArtifactEntry {
    /**
     * Stage ID in `node@visit` form.
     */
    'stage_id': string;
    /**
     * Node slug that produced the artifact.
     */
    'node_slug': string;
    /**
     * Retry attempt number.
     */
    'retry': number;
    /**
     * Artifact path relative to the stage artifact capture directory.
     */
    'relative_path': string;
    /**
     * Artifact size in bytes.
     */
    'size': number;
}
