/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BlockedReason } from './blocked-reason';

export interface RunStatusPaused {
    'kind': RunStatusPausedKindEnum;
    'prior_block': BlockedReason | null;
}

export const RunStatusPausedKindEnum = {
    PAUSED: 'paused'
} as const;

export type RunStatusPausedKindEnum = typeof RunStatusPausedKindEnum[keyof typeof RunStatusPausedKindEnum];
