/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Serializable snapshot of execution state for crash recovery and resume.
 */
export interface RunCheckpoint {
    /**
     * ISO 8601 timestamp when the checkpoint was created.
     */
    'timestamp': string;
    /**
     * Identifier of the node being executed at checkpoint time.
     */
    'current_node': string;
    /**
     * Identifiers of nodes that have completed execution.
     */
    'completed_nodes': Array<string>;
    /**
     * Map of node identifier to retry count.
     */
    'node_retries': { [key: string]: number; };
    /**
     * Key-value context map accumulated during execution.
     */
    'context_values': { [key: string]: any; };
    /**
     * Map of node identifier to outcome data for goal gate checks after resume.
     */
    'node_outcomes'?: { [key: string]: any; };
    /**
     * The node to resume execution at after this checkpoint.
     */
    'next_node_id'?: string;
    /**
     * SHA of the git commit created at this checkpoint.
     */
    'git_commit_sha'?: string;
    /**
     * Failure signature counts within the main loop.
     */
    'loop_failure_signatures'?: { [key: string]: any; };
    /**
     * Failure signature counts across loop_restart edges.
     */
    'restart_failure_signatures'?: { [key: string]: any; };
}
