/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Properties for the `run.superseded_by` audit event emitted on a rewound source run after archive succeeds.
 */
export interface RunSupersededByProps {
    'new_run_id': string;
    'target_checkpoint_ordinal': number;
    'target_node_id': string;
    'target_visit': number;
}
