/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface RunGoalInline {
    'type': RunGoalInlineTypeEnum;
    /**
     * Resolved config string that may contain env interpolation tokens.
     */
    'value': string;
}

export const RunGoalInlineTypeEnum = {
    INLINE: 'inline'
} as const;

export type RunGoalInlineTypeEnum = typeof RunGoalInlineTypeEnum[keyof typeof RunGoalInlineTypeEnum];
