/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A directory entry in a run sandbox.
 */
export interface SandboxFileEntry {
    /**
     * Basename of the entry.
     */
    'name': string;
    /**
     * Whether the entry is a directory.
     */
    'is_dir': boolean;
    /**
     * File size in bytes when known.
     */
    'size'?: number;
}
