/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A saved SQL query for the insights editor.
 */
export interface SavedQuery {
    /**
     * Unique query identifier.
     */
    'id': string;
    /**
     * Human-readable query name.
     */
    'name': string;
    /**
     * SQL query text.
     */
    'sql': string;
    /**
     * Timestamp when the query was saved.
     */
    'created_at': string;
    /**
     * Timestamp when the query was last modified.
     */
    'updated_at': string;
}
