/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ServerListenUnixSettings {
    'type': ServerListenUnixSettingsTypeEnum;
    'path': string;
}

export const ServerListenUnixSettingsTypeEnum = {
    UNIX: 'unix'
} as const;

export type ServerListenUnixSettingsTypeEnum = typeof ServerListenUnixSettingsTypeEnum[keyof typeof ServerListenUnixSettingsTypeEnum];
