/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Canonical workflow stage handler kind.
 */

export const StageHandler = {
    START: 'start',
    EXIT: 'exit',
    AGENT: 'agent',
    PROMPT: 'prompt',
    COMMAND: 'command',
    HUMAN: 'human',
    CONDITIONAL: 'conditional',
    PARALLEL: 'parallel',
    PARALLEL_FAN_IN: 'parallel.fan_in',
    STACK_MANAGER_LOOP: 'stack.manager_loop',
    WAIT: 'wait'
} as const;

export type StageHandler = typeof StageHandler[keyof typeof StageHandler];
