/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Terminal execution outcome of a workflow stage.
 */

export const StageOutcome = {
    SUCCEEDED: 'succeeded',
    PARTIALLY_SUCCEEDED: 'partially_succeeded',
    FAILED: 'failed',
    SKIPPED: 'skipped'
} as const;

export type StageOutcome = typeof StageOutcome[keyof typeof StageOutcome];
