/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SubAgentStatusClosed } from './sub-agent-status-closed';
// May contain unused imports in some cases
// @ts-ignore
import type { SubAgentStatusCompleted } from './sub-agent-status-completed';
// May contain unused imports in some cases
// @ts-ignore
import type { SubAgentStatusFailed } from './sub-agent-status-failed';
// May contain unused imports in some cases
// @ts-ignore
import type { SubAgentStatusRunning } from './sub-agent-status-running';

/**
 * @type SubAgentStatus
 * Projected lifecycle status for a subagent.
 */
export type SubAgentStatus = { kind: 'closed' } & SubAgentStatusClosed | { kind: 'completed' } & SubAgentStatusCompleted | { kind: 'failed' } & SubAgentStatusFailed | { kind: 'running' } & SubAgentStatusRunning;
