/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SubAgentStatus } from './sub-agent-status';

/**
 * Current projected state for one subagent spawned by an agent stage.
 */
export interface SubAgentProjection {
    'agent_id': string;
    'depth': number;
    'task': string;
    'status': SubAgentStatus;
}
