/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SubmitAnswerMultiSelectedRequest {
    /**
     * Multiple selected option answer.
     */
    'kind': SubmitAnswerMultiSelectedRequestKindEnum;
    /**
     * Keys of selected options.
     */
    'option_keys': Array<string>;
}

export const SubmitAnswerMultiSelectedRequestKindEnum = {
    MULTI_SELECTED: 'multi_selected'
} as const;

export type SubmitAnswerMultiSelectedRequestKindEnum = typeof SubmitAnswerMultiSelectedRequestKindEnum[keyof typeof SubmitAnswerMultiSelectedRequestKindEnum];
