/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SubmitAnswerMultiSelectedRequest } from './submit-answer-multi-selected-request';
// May contain unused imports in some cases
// @ts-ignore
import type { SubmitAnswerNoRequest } from './submit-answer-no-request';
// May contain unused imports in some cases
// @ts-ignore
import type { SubmitAnswerSelectedRequest } from './submit-answer-selected-request';
// May contain unused imports in some cases
// @ts-ignore
import type { SubmitAnswerTextRequest } from './submit-answer-text-request';
// May contain unused imports in some cases
// @ts-ignore
import type { SubmitAnswerYesRequest } from './submit-answer-yes-request';

/**
 * @type SubmitAnswerRequest
 * Request body for submitting an answer to a pending question. The `kind` discriminator determines which answer shape is submitted.
 */
export type SubmitAnswerRequest = { kind: 'multi_selected' } & SubmitAnswerMultiSelectedRequest | { kind: 'no' } & SubmitAnswerNoRequest | { kind: 'selected' } & SubmitAnswerSelectedRequest | { kind: 'text' } & SubmitAnswerTextRequest | { kind: 'yes' } & SubmitAnswerYesRequest;
