/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Reason attached to a successful terminal run status.
 */

export const SuccessReason = {
    COMPLETED: 'completed',
    PARTIAL_SUCCESS: 'partial_success'
} as const;

export type SuccessReason = typeof SuccessReason[keyof typeof SuccessReason];
