/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Checkpoint timeline entry for a run.
 */
export interface TimelineEntryResponse {
    'ordinal': number;
    'node_name': string;
    'visit': number;
    'checkpoint_seq': number;
    'run_commit_sha'?: string | null;
}
