/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const TlsMode = {
    VERIFY: 'verify',
    NO_VERIFY: 'no_verify',
    FALSE: 'false'
} as const;

export type TlsMode = typeof TlsMode[keyof typeof TlsMode];
