/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const WebhookStrategy = {
    TAILSCALE_FUNNEL: 'tailscale_funnel',
    SERVER_URL: 'server_url'
} as const;

export type WebhookStrategy = typeof WebhookStrategy[keyof typeof WebhookStrategy];
