/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProjectNamespace } from './project-namespace';
// May contain unused imports in some cases
// @ts-ignore
import type { RunNamespace } from './run-namespace';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkflowNamespace } from './workflow-namespace';

/**
 * The persisted dense `WorkflowSettings` snapshot used for a specific run. This matches the resolved run settings recorded at launch time.
 */
export interface WorkflowSettings {
    'project': ProjectNamespace;
    'workflow': WorkflowNamespace;
    'run': RunNamespace;
}
