/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface WorkflowRef {
    'slug': string | null;
    'name': string | null;
    'graph_name': string | null;
    /**
     * Number of nodes in the workflow graph.
     */
    'node_count': number;
    /**
     * Number of edges in the workflow graph.
     */
    'edge_count': number;
}
